# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

# Much of the information is available via:
context:
  group: mumble-voip
  name: mumble
  version: 1.5.735
  git_rel: github.com/${{ group }}/${{ name }}

package:
  name: mumble-voip
  version: ${{ version }}
  
source:
  - url: https://github.com/mumble-voip/mumble/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 539680318419ca6c236d129dc5b6a96878bd048957cfcfb3882d313dd16660fa
    target_directory: src/mumble
    patches:
      - patches/0001-find-python.patch
  - url: https://raw.githubusercontent.com/Krzmbrzl/FindPythonInterpreter/refs/heads/main/FindPythonInterpreter.cmake
    sha256: e50f46754aa5d3e72f18a37ffdf077bc6de1600e6c460d8e0184924be631c93d
    target_directory: src/mumble/3rdparty/FindPythonInterpreter/
  - url: https://raw.githubusercontent.com/Krzmbrzl/cmake-compiler-flags/refs/heads/main/CompilerFlags.cmake
    sha256: 0636e048208bb37f07747136c00eec6f62549fe7147abf02a451df60702c3f89
    target_directory: src/mumble/3rdparty/cmake-compiler-flags/
  - url: https://github.com/lipis/flag-icons/archive/refs/tags/v7.3.2.tar.gz
    sha256: 6a5497e1029e66415c3941a5e5ee001944b0a7e46bf365c6d5a91a033acee87e
    target_directory: src/mumble/3rdparty/flag-icons/
  - url: https://github.com/microsoft/GSL/archive/refs/tags/v4.1.0.tar.gz
    sha256: 0a227fc9c8e0bf25115f401b9a46c2a68cd28f299d24ab195284eb3f1d7794bd 
    target_directory: src/mumble/3rdparty/gsl/
  - url: https://github.com/nlohmann/json/archive/refs/tags/v3.11.3.tar.gz
    sha256: 0d8ef5af7f9794e3263480193c491549b2ba6cc74bb018906202ada498a79406
    target_directory: src/mumble/3rdparty/nlohmann_json/
  - url: https://github.com/wolfpld/tracy/archive/refs/tags/v0.11.1.tar.gz
    sha256: 2c11ca816f2b756be2730f86b0092920419f3dabc7a7173829ffd897d91888a1
    target_directory: src/mumble/3rdparty/tracy/

# https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/README.md
build:
  number: 0
  script:
    env:
      JOB_CNT: ${{ nprocs }}   
    interpreter: nu
    content: |
      cd src/mumble
      cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -Dspeechd=OFF -Dstatic=ON -Doverlay-xcompile=OFF
      cd build
      cmake --build . -j $env.JOB_CNT
      cmake --install .
      
requirements:
  build:
    - nushell
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    # - ${{ stdlib('c') }}
    # - qt6-main
    - qt
    - qt-main
    # - qt-wayland
    - mesalib
    - xorg-libxext
    - libxext-devel-conda-x86_64
    - python
    - cmake 
    - py-build-cmake
    - ninja
    - if: unix
      then: make
    - pkg-config
    - libopenssl-static
    - libprotobuf-static
    - protobuf
  host:
    # - ${{ stdlib('c') }}
    # - qt
    # - qt6-main
    # - qt6-wayland 
    - xorg-libxi
    - libboost-devel
    - libgl-devel
    - alsa-lib
    - libcap
    - libogg
    - libsndfile
    - libopus
    # - libspeechd
    - avahi
    - libxcb
    - zeroconf
    - poco

tests:
  - script: 
      - "mumble --help 2>&1"

about:
  homepage: https://www.mumble.info/
  summary: 'Mumble is a free, open source, low latency, high quality voice chat application.'
  description: |
     Mumble was the first VoIP application to establish true low latency voice communication over a decade ago.
     But low latency and gaming are not the only use cases it shines in.
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - https://www.mumble.info/LICENSE
    - src/mumble/3rdPartyLicenses
  documentation: https://www.mumble.info/documentation/
  repository: https://github.com/mumble-voip/mumble

extra:
  recipe-maintainers:
    - phreed
