context:
  version: 2.08

package:
  name: pwgen
  version: ${{ version }}

source:
  url: https://github.com/tytso/pwgen/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 8d6e94f28655e61d6126290e3eafad4d17d7fba0d0d354239522a740a270bb2f

build:
  number: 0
  script: |
    autoreconf -i 
    find . -maxdepth 2
    ./configure --disable-debug --disable-dependency-tracking \
                --prefix=$PREFIX \
                --mandir=$PREFIX/share/man
    make
    make install

requirements:
  build:
    - ${{ compiler('c') }}
    # - ${{ stdlib('c') }}
    - autoconf
    - automake
    - make

tests:
  - script:
      - pwgen --secure 20 10

about:
  homepage: https://pwgen.sourceforge.net/
  license: GPL-2.0-only
  license_file: 
    - debian/copyright
  summary: Password generator
  description: |
    pwgen generates random, meaningless but pronounceable passwords.
    These passwords contain either only lowercase letters, or upper
    and lower case mixed, or digits thrown in.
  repository: https://sourceforge.net/projects/pwgen/
  
extra:
  recipe-maintainers:
    - phreed
