# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 4.7.1
  python_min: 3.11

package:
  name: flask-jwt-extended
  version: ${{ version }}

source:
  url: https://github.com/vimalloc/flask-jwt-extended/archive/refs/tags/${{ version }}.tar.gz
  sha256: c5bba87248b2253537891511f928dd3b51faf74e8e5ec1746529a6a36d819b9a

build:
  noarch: python
  script: pip install . -v

requirements:
  host:
    - pip
    - python ==${{ python_min }}
    - setuptools
    - wheel
  run:
    - python >=${{ python_min }},<4.0.0
    - flask >=2.0,<4.0
    - pyjwt >=2.0,<3.0
    - werkzeug >=0.14
  run_exports:
    weak:
      - ${{ pin_subpackage("flask-jwt-extended", upper_bound="x.x") }}

tests:
  - python:
      imports:
        - flask_jwt_extended
  - script:
      - python -c "import flask_jwt_extended"
    requirements:
      run:
        - python ${{ python_min }}

about:
  homepage: https://github.com/vimalloc/flask-jwt-extended
  summary: An open source Flask extension
  description: |
    A Flask JWT extension that supports refresh tokens,
    blacklisting/revoking tokens,
    and token freshness (for accessing critical views).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - phreed
