# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 1.14.0

package:
  name: bibtex-tidy
  version: ${{ version }}

source:
  - url: https://registry.npmjs.org/bibtex-tidy/-/bibtex-tidy-${{ version }}.tgz
    sha256: 0a2c1bb73911a7cee36a30ce1fc86feffe39b2d39acd4c94d02aac6f84a00285
    # we do not extract the source code and install the tarball directly as that works better
    file_name: bibtex-tidy-${{ version }}.tgz
  - path: ../../.scripts/npm_licenses.nu
    file_name: npm_licenses.nu

build:
  script:
    interpreter: nu
    content: |
      $"building ($env.PKG_NAME)!"
      npm install -g ./bibtex-tidy-${{ version }}.tgz --prefix $env.PREFIX
      source npm_licenses.nu
      main | save license_summary.txt

requirements:
  build:
    - nushell
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - bibtex-tidy --version

about:
  homepage: https://.org
  summary: bibtex summary
  description: |
    Bibtex description
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-summary.txt
  documentation: https://.org/docs/
  repository: https://github.com/

extra:
  recipe-maintainers:
    - maintainer
