# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.0.11_alpha.1"

package:
  name: iamb
  version: ${{ version }}

source:
  url: https://github.com/ulyssa/iamb/archive/refs/heads/main.tar.gz
  sha256: 6be8c76aaca45f7971bcb542b1d12f26cd5f2c6266202de6433d768034e62fc7

build:
  number: 0
  script:
    interpreter: nu
    content: |
      $env.LIBSQLITE3_SYS_USE_PKG_CONFIG = "1"
      $env.VERGEN_GIT_SHA = "${{ env.get('CONDA_PREFIX') }}"
      ^cargo install --root ($env.PREFIX) --path .

requirements:
  build:
    - nushell
    - pkgconf
    - rust
  host:
    - sqlite
  run:
    - if: linux
      then:
        - openssl

tests:
  # Test 1: Verify package contents are included
  - package_contents:
      files:
        # iamb binary
        - ${{ "Library/" if win }}bin/iamb${{ ".exe" if win }}

  # Test 2: Functional tests
  - requirements:
      build:
        - nushell
    script:
      interpreter: nu
      content:
        - ^iamb --version

about:
  homepage: https://iamb.chat
  license: Apache-2.0
  license_file:
    - LICENSE
  summary: Matrix client for Vim addicts
  description: |
    iamb is a Matrix client for the terminal that uses Vim keybindings.
  repository: https://github.com/ulyssa/iamb

extra:
  recipe-maintainers:
    - phreed
