# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.10.1"

package:
  name: dysk
  version: ${{ version }}

source:
  url: https://api.github.com/repos/Canop/dysk/tarball/refs/tags/v2.10.1
  sha256: ac77cd0ed28bef37826feee9adc770a8af9b8f410397d9dd0370dd8797266ead

build:
  number: 0
  script:
    interpreter: nu
    content: |
      # Expand the GitHub API tarball which comes as a single file
      let tarball_file = (ls | where type == file and name =~ "\\.tar\\.gz$|^v2\\.10\\.1$" | first | get name)
      ^tar -xzf $tarball_file

      # Find the extracted directory (GitHub API tarballs create directories like "Canop-dysk-abc123")
      let extracted_dir = (ls | where type == dir and name =~ "Canop-dysk-" | first | get name)

      # Change to the extracted directory and build
      cd $extracted_dir
      ^cargo install --root ($env.PREFIX) --path .

requirements:
  build:
    - nushell
    - tar
    - rust
  host:
    - rust
  run:
    # - if: linux
    #   then:
    #     - linux-only-dependency

tests:
  # Test 1: Verify package contents are included
  - package_contents:
      files:
        # Dysk binary
        - ${{ "Library/" if win }}bin/dysk${{ ".exe" if win }}

    # Test 2: Functional tests
  - requirements:
      build:
        - nushell
    script:
      interpreter: nu
      content: |
        ^dysk -s free-d | ^grep "filesystem"
        ^dysk --version | ^grep ${{ version }}

about:
  homepage: https://dystroy.org/dysk/
  license: MIT
  license_file: "Canop-dysk-*/LICENSE"
  summary: Linux utility to get information on filesystems, like df but better
  repository: https://github.com/Canop/dysk

extra:
  recipe-maintainers:
    - phreed

  version:
    github-tags:
      - ^(\d+\.\d+\.\d+)$
