# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

# Much of the information is available via:
#  pnpm info node-red
# The sha256 is currently not available from these sources. 
context:
  name: node-red
  version: "4.0.9"

package:
  name: node-red
  version: ${{ version }}

source:
  - url: https://github.com/node-red/node-red/archive/refs/tags/${{ version }}.tar.gz
    sha256: d3386f45d336bc1987e63a8e594e353c71e50a12c9c6d7e36c4b31af6cccfc19
  - if: linux
    then: 
      path: systemd/configure-service.sh
      target_directory: systemd/configure-node-red.sh
 
build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - grunt
    - pnpm
    - pnpm-licenses
  host:
    - nodejs
    - grunt
  run:
    - nodejs

tests:
  - script:
      - "find . -maxdepth 2" 
      - "node-red --help 2>&1"

about:
  homepage: https://nodered.org
  summary: 'Low-code programming for event-driven applications'
  description: |
     Node-RED's goal is to enable anyone to build applications that collect,
     transform and visualize their data; 
     building flows that can automate their world. 
     Its low-code nature makes it accessible to users of any background, 
     whether for home automation,
     industrial control systems or anything in between.
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - https://github.com/node-red/node-red/blob/master/LICENSE
    - third-party-licenses.txt
  documentation: https://nodered.org/docs/
  repository: https://github.com/node-red/node-red

extra:
  recipe-maintainers:
    - phreed
