"$schema" = "https://pixi.sh/v0.45.0/schema/manifest/schema.json"

[workspace]
name = "meso-forge"
version = "0.1.0"
description = "Packages needed by my projects"
authors = [
  "Wolf Vollprecht <w.vollprecht@gmail.com>", 
  "Fred Eisele <fred.eisele@vanderbilt.edu>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]
preview = ["pixi-build"]

[tasks.clean-all]
cmd = ["rm", "-rf", "pkgs-out", "wip-out"]

[feature.update-ver.dependencies]
python = "3.12.*"
requests = ">=2.32.3,<3"
pyyaml = ">=6.0.2,<7"
semver = ">=3.0.2,<4"

[feature.update-ver.tasks.update-ver]
cmd = ["python", ".scripts/update-versions.py" ]

[feature.build.dependencies]
rattler-build = ">=0.39.0,<1"

[feature.build.tasks.build]
cmd = [
  "rattler-build", "build",
  "--recipe-dir", "./{{ pkg-dir }}/{{ pkg }}",
  "--output-dir", "./{{ pkg-dir }}-out",
  "--skip-existing=all",
  "--target-platform={{ target-platform }}",
  "--channel", "https://prefix.dev/meso-forge",
  "--channel", "conda-forge",
  "-vvv",
]
args =  [
  { "arg" = "pkg", "default" = "" },
  { "arg" = "pkg-dir", "default" = "pkgs" },
  { "arg" = "target-platform", "default" = "linux-64" },
]

[feature.build.tasks.build-wip-all]
depends-on = [{ "task" = "build", "args" = ["", "wip", "linux-64"] }]

[feature.upload-all.dependencies]
nushell = ">=0.103.0,<1"

[feature.upload-all.tasks.upload-all]
cmd = [ 
  "nu", ".scripts/upload-all.nu",
  "./{{ pkg-dir }}-out",
]

[environments]
update = { features = ["update-ver"] }
build = { features = ["build"] }
upload = { features = ["upload-all"] }

