"$schema" = "https://pixi.sh/latest/schema/manifest/schema.json"

[workspace]
name = "meso-forge"
version = "0.1.0"
description = "Packages needed by my projects"
authors = [
  "Wolf Vollprecht <w.vollprecht@gmail.com>", 
  "Fred Eisele <fred.eisele@vanderbilt.edu>"]
channels = ["conda-forge"]
platforms = [
  # "osx-arm64", 
  "linux-64", 
  # "win-64", 
  # "osx-64",
  ]
preview = ["pixi-build"]

[dependencies]
rattler-build = ">=0.40.0,<0.41"
nushell = ">=0.103.0,<0.104"

[tasks.clean]
cmd = ["rm", "-rf", "pkgs-out"]


[tasks.build-the]
cmd = [
  "rattler-build", "build",
  "--recipe-dir", "./pkgs/{{ pkg }}",
  "--output-dir", "./pkgs-out",
  "--skip-existing=all",
  "--target-platform={{ target-platform }}",
  "--channel", "https://prefix.dev/meso-forge",
  "--channel", "conda-forge",
  "-vvv",
]
args =  [
  { "arg" = "pkg", "default" = "_skeleton" },
  { "arg" = "target-platform", "default" = "linux-64" },
]

[tasks.build-skeletons]
depends-on = [
  { "task" = "build-the", "args" = ["_skeleton_js", "linux-64"] },
  { "task" = "build-the", "args" = ["_skeleton_python", "linux-64"] },
  { "task" = "build-the", "args" = ["_skeleton_rust", "linux-64"] },
]

[tasks.build]
depends-on = [
  # { "task" = "build-the", "args" = ["asciidoctor-reveal.js", "linux-64"] },
  { "task" = "build-the", "args" = ["asyncio", "linux-64"] },
  { "task" = "build-the", "args" = ["bash-preexec", "linux-64"] },
  # { "task" = "build-the", "args" = ["bitwarden-cli", "linux-64"] },
  # { "task" = "build-the", "args" = ["devcontainer-cli", "linux-64"] },
  { "task" = "build-the", "args" = ["digitalpy", "linux-64"] },
  { "task" = "build-the", "args" = ["dysk", "linux-64"] },
  { "task" = "build-the", "args" = ["fd", "linux-64"] },
  { "task" = "build-the", "args" = ["flask-jwt-extended", "linux-64"] },
  { "task" = "build-the", "args" = ["testresources", "linux-64"] },
  { "task" = "build-the", "args" = ["freetakserver", "linux-64"] },
  { "task" = "build-the", "args" = ["freetakserver-ui", "linux-64"] },
  { "task" = "build-the", "args" = ["fsarchiver", "linux-64"] },
  # { "task" = "build-the", "args" = ["iamb", "linux-64"] },
  # { "task" = "build-the", "args" = ["internxt", "linux-64"] },
  # { "task" = "build-the", "args" = ["jank", "linux-64"] },
  # { "task" = "build-the", "args" = ["kombose", "linux-64"] },
  # { "task" = "build-the", "args" = ["mediamtx", "linux-64"] },
  # { "task" = "build-the", "args" = ["metashell", "linux-64"] },
  # { "task" = "build-the", "args" = ["mumble", "linux-64"] },
  # { "task" = "build-the", "args" = ["neovide", "linux-64"] },
  { "task" = "build-the", "args" = ["node-red", "linux-64"] },
  { "task" = "build-the", "args" = ["node-red-contrib-web-worldmap", "linux-64"] },
  { "task" = "build-the", "args" = ["pwgen", "linux-64"] },
  { "task" = "build-the", "args" = ["ratatui", "linux-64"] },
  # { "task" = "build-the", "args" = ["systemd-pixi-generator", "linux-64"] },
  ]

[tasks.publish-all]
cmd = [ 
  "nu",
  ".scripts/publish-all.nu",
  "./pkgs-out",
]

[feature.update-ver.dependencies]
python = "3.12.*"
requests = ">=2.32.3,<3"
pyyaml = ">=6.0.2,<7"
semver = ">=3.0.2,<4"

[feature.update-ver.tasks.update-ver]
cmd = ["python", ".scripts/update-versions.py" ]

[environments]
update = { features = ["update-ver"]}
