"$schema" = "https://pixi.sh/latest/schema/manifest/schema.json"

[workspace]
name = "meso-forge"
version = "0.1.0"
description = "Packages needed by my projects"
authors = [
  "Wolf Vollprecht <w.vollprecht@gmail.com>", 
  "Fred Eisele <fred.eisele@vanderbilt.edu>"]
channels = ["conda-forge"]
platforms = [
  # "osx-arm64", 
  "linux-64", 
  # "win-64", 
  # "osx-64",
  ]
preview = ["pixi-build"]

[dependencies]
rattler-build = ">=0.40.0,<0.41"
nushell = ">=0.103.0,<0.104"

[tasks.clean-the]
args =  [
  { arg = "pkg", default = "_skeleton_python" },
  { arg = "tgt_platform", default = "linux-64" },
]
cmd = ["rm", "pkgs-out/*/{{ pkg }}*.conda"]

[tasks.clean]
cmd = ["rm", "-rf", "pkgs-out"]


[tasks.build-the]
args =  [
  { arg = "pkg", default = "_skeleton_python" },
  { arg = "tgt_platform", default = "linux-64" },
]
cmd = [
  "rattler-build", "build",
  "--recipe-dir", "./pkgs/{{ pkg }}",
  "--output-dir", "./pkgs-out",
  "--skip-existing=all",
  "--target-platform={{ tgt_platform }}",
  "--channel", "https://prefix.dev/meso-forge",
  "--channel", "conda-forge",
  "-vvv",
]

[tasks.build-skeletons]
depends-on = [
  { task = "build-the", args = ["_skeleton_js", "linux-64"] },
  { task = "build-the", args = ["_skeleton_python", "linux-64"] },
  { task = "build-the", args = ["_skeleton_rust", "linux-64"] },
]

[tasks.build]
depends-on = [
  # { task = "build-the", environment = "wip", args = ["asciidoctor-reveal.js", "linux-64"] },
  { task = "build-the", environment = "default", args = ["asyncio", "linux-64"] },
  { task = "build-the", environment = "default", args = ["bash-preexec", "linux-64"] },
  # { task = "build-the", environment = "wip", args = ["bitwarden-cli", "linux-64"] },
  # { task = "build-the", environment = "wip", args = ["devcontainer-cli", "linux-64"] },
  { task = "build-the", environment = "default", args = ["digitalpy", "linux-64"] },
  { task = "build-the", environment = "default", args = ["dysk", "linux-64"] },
  { task = "build-the", environment = "default", args = ["fd", "linux-64"] },
  { task = "build-the", environment = "default", args = ["flask-jwt-extended", "linux-64"] },
  { task = "build-the", environment = "default", args = ["testresources", "linux-64"] },
  { task = "build-the", environment = "default", args = ["freetakserver", "linux-64"] },
  { task = "build-the", environment = "default", args = ["freetakserver-ui", "linux-64"] },
  { task = "build-the", environment = "default", args = ["fsarchiver", "linux-64"] },
  # { task = "build-the", environment = "wip", args = ["iamb", "linux-64"] },
  # { task = "build-the", environment = "wip", args = ["internxt", "linux-64"] },
  # { task = "build-the", environment = "wip", args = ["jank", "linux-64"] },
  # { task = "build-the", environment = "wip", args = ["kombose", "linux-64"] },
  # { task = "build-the", environment = "wip", args = ["mediamtx", "linux-64"] },
  # { task = "build-the", environment = "wip", args = ["metashell", "linux-64"] },
  # { task = "build-the", environment = "wip", args = ["mumble", "linux-64"] },
  # { task = "build-the", environment = "wip", args = ["neovide", "linux-64"] },
  { task = "build-the", environment = "default", args = ["node-red", "linux-64"] },
  { task = "build-the", environment = "default", args = ["node-red-worldmap", "linux-64"] },
  { task = "build-the", environment = "default", args = ["pwgen", "linux-64"] },
  { task = "build-the", environment = "default", args = ["ratatui", "linux-64"] },
  # { task = "build-the", environment = "wip", args = ["systemd-pixi-generator", "linux-64"] },
  ]

[tasks.publish-the]
args =  [
  { arg = "pkg", default = "_skeleton_python" },
  { arg = "tgt_platform", default = "linux-64" },
]
# the upload expects the RATTLER_AUTH_FILE variable to be set
cmd = [
  "rattler-build", "upload", "prefix",
  "--skip-existing", "-vvv",
  "--channel", "meso-forge",
  "pkgs-out/*/{{ pkg }}*.conda",
]
# depends-on = [
#   { task = "build-the", args = ['{{ pkg }}', "linux-64"] },
# ]

[tasks.publish]
depends-on = [
  # { task = "publish-the", environment = "wip", args = ["asciidoctor-reveal.js", "linux-64"] },
  { task = "publish-the", environment = "default", args = ["asyncio", "noarch"] },
  { task = "publish-the", environment = "default", args = ["bash-preexec", "linux-64"] },
  # { task = "publish-the", environment = "wip", args = ["bitwarden-cli", "linux-64"] },
  # { task = "publish-the", environment = "wip", args = ["devcontainer-cli", "linux-64"] },
  { task = "publish-the", environment = "default", args = ["digitalpy", "linux-64"] },
  # { task = "publish-the", environment = "wip", args = ["dysk", "linux-64"] },
  # { task = "publish-the", environment = "wip", args = ["fd", "linux-64"] },
  { task = "publish-the", environment = "default", args = ["flask-jwt-extended", "linux-64"] },
  { task = "publish-the", environment = "default", args = ["testresources", "linux-64"] },
  { task = "publish-the", environment = "default", args = ["freetakserver", "linux-64"] },
  { task = "publish-the", environment = "default", args = ["freetakserver-ui", "linux-64"] },
  # { task = "publish-the", environment = "wip", args = ["fsarchiver", "linux-64"] },
  # { task = "publish-the", environment = "wip", args = ["iamb", "linux-64"] },
  # { task = "publish-the", environment = "wip", args = ["internxt", "linux-64"] },
  # { task = "publish-the", environment = "wip", args = ["jank", "linux-64"] },
  # { task = "publish-the", environment = "wip", args = ["kombose", "linux-64"] },
  # { task = "publish-the", environment = "wip", args = ["mediamtx", "linux-64"] },
  # { task = "publish-the", environment = "wip", args = ["metashell", "linux-64"] },
  # { task = "publish-the", environment = "wip", args = ["mumble", "linux-64"] },
  # { task = "publish-the", environment = "wip", args = ["neovide", "linux-64"] },
  { task = "publish-the", environment = "default", args = ["node-red", "linux-64"] },
  { task = "publish-the", environment = "default", args = ["node-red-worldmap", "linux-64"] },
  # { task = "publish-the", environment = "wip", args = ["pwgen", "linux-64"] },
  { task = "publish-the", environment = "default", args = ["ratatui", "linux-64"] },
  # { task = "publish-the", environment = "wip", args = ["systemd-pixi-generator", "linux-64"] },
  ]


[feature.update-ver.dependencies]
python = "3.12.*"
requests = ">=2.32.3,<3"
pyyaml = ">=6.0.2,<7"
semver = ">=3.0.2,<4"

[feature.update-ver.tasks.update-ver]
cmd = ["python", ".scripts/update-versions.py" ]

[environments.update]
features = ["update-ver"]

[environments.wip]
features = ["update-ver"]
no-default-feature = true
