# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.30.0

package:
  name: ratatui
  version: ${{ version }}

source:
  url: https://api.github.com/repos/ratatui/ratatui/tarball/ratatui-v0.30.0-alpha.4
  sha256: e0c177d5830559cba0a73100a10810f596572ea4d4550bccc9e5d1437e9e1fd7

build:
  script:
    interpreter: nu
    content: |
      # Expand the GitHub API tarball which comes as a single file
      let tarball_file = (ls | where type == file and name =~ "\\.tar\\.gz$|^ratatui-v0\\.30\\.0-alpha\\.4$" | first | get name)
      ^tar -xzf $tarball_file

      # Find the extracted directory (GitHub API tarballs create directories like "ratatui-ratatui-abc123")
      let extracted_dir = (ls | where type == dir and name =~ "ratatui-ratatui-" | first | get name)

      # Change to the extracted directory and build
      cd $extracted_dir

      # This is a Rust library crate - we just validate it compiles
      # The actual library would be used via Cargo.toml dependencies

      # Build the main ratatui library to validate it works
      cargo check --release --manifest-path Cargo.toml

      # Create a minimal marker file to indicate the package was built
      mkdir ($env.PREFIX | path join "share")
      echo "ratatui v${{ version }} - Terminal UI library for Rust" | save ($env.PREFIX | path join "share" "ratatui-info.txt")

requirements:
  build:
    - nushell
    - tar
    - rust
    - pkgconf

tests:
  # Test 1: Verify package contents are included
  - package_contents:
      files:
        # Marker file indicating successful build
        - share/ratatui-info.txt

    # Test 2: Functional test
  - requirements:
      build:
        - nushell
    script:
      interpreter: nu
      content:
        # Simple validation test
        - if ($env.PREFIX | path join "share" "ratatui-info.txt" | path exists) { echo "✓ Package marker found" } else { exit 1 }
        - echo "✓ Ratatui package test passed"

about:
  homepage: https://ratatui.rs
  license: MIT
  license_file:
    - LICENSE
  summary: A Rust crate for cooking TUIs
  description: |
    Ratatui is a Rust crate for cooking up terminal user interfaces (TUIs).
    It provides a simple and flexible way to create text-based user interfaces in the terminal.

    Note: This conda package serves as a validation that ratatui can compile in this environment.
    For actual development, add ratatui as a dependency in your Cargo.toml file.
  documentation: https://docs.rs/ratatui/latest/ratatui/
  repository: https://github.com/ratatui/ratatui

extra:
  recipe-maintainers:
    - phreed
