# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.30.0

package:
  name: ratatui
  version: ${{ version }}

source:
  url: https://api.github.com/repos/ratatui/ratatui/tarball/ratatui-v0.30.0-alpha.4
  sha256: e0c177d5830559cba0a73100a10810f596572ea4d4550bccc9e5d1437e9e1fd7

build:
  number: 0
  noarch: generic
  script:
    interpreter: nu
    content: |
      # This is a Rust library crate - we just validate it compiles
      # The actual library would be used via Cargo.toml dependencies

      # Build the main ratatui library to validate it works
      cargo check --release --manifest-path Cargo.toml

      # Create a minimal marker file to indicate the package was built
      mkdir ($env.PREFIX | path join "share")
      echo "ratatui v${{ version }} - Terminal UI library for Rust" | save ($env.PREFIX | path join "share" "ratatui-info.txt")

requirements:
  build:
  - nushell
  - rust
  - pkgconf

tests:
  # Test 1: Verify package marker file is included
- package_contents:
    files:
    - share/ratatui-info.txt

  # Test 2: Functional validation
- requirements:
    build:
    - nushell
    - rust
  script:
    interpreter: nu
    content:
        # Simple validation test
    - if ($env.PREFIX | path join "share" "ratatui-info.txt" | path exists) { echo "✓ Package marker found" } else { exit 1 }
    - echo "✓ Ratatui package test passed"

about:
  homepage: https://ratatui.rs
  license: MIT
  license_file:
  - LICENSE
  summary: A Rust crate for cooking TUIs
  description: |
    Ratatui is a Rust crate for cooking up terminal user interfaces (TUIs).
    It provides a simple and flexible way to create text-based user interfaces in the terminal.

    Note: This conda package serves as a validation that ratatui can compile in this environment.
    For actual development, add ratatui as a dependency in your Cargo.toml file.
  documentation: https://docs.rs/ratatui/latest/ratatui/
  repository: https://github.com/ratatui/ratatui

extra:
  recipe-maintainers:
  - phreed
