# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/73cd2eed94c576213c5f25ab57adf6d8c83e792a/schema.json
schema_version: 1

context:
  version: 0.30.0

package:
  name: ratatui
  version: ${{ version }}

source:
  url: https://github.com/ratatui/ratatui/archive/refs/tags/ratatui-v${{ version }}-alpha.2.tar.gz
  sha256: 047398b1b54f790ac084eb3be33864110d59fde8010e06a6b5d96578e37845f6 

build:
  number: 0
  script: |
    cargo build
    # cargo install --root $PREFIX --path .

requirements:
  build:
    - pkgconf
    - rust
  # run_exports:
  #   - ${{ pin_subpackage(name, upper_bound="x.x") }}

tests:
  - script: |
      echo "how to test ratatui"

about:
  homepage: https://ratatui.rs
  license: MIT 
  license_file: 
    - LICENSE
  summary: A Rust crate for cooking TUIs
  description: |
    Ratatui (ˌræ.təˈtu.i) is a Rust crate for cooking up terminal user interfaces (TUIs). 
    It provides a simple and flexible way to create text-based user interfaces in the terminal, 
    which can be used for command-line applications, dashboards, and other interactive console programs.
  documentation: https://docs.rs/ratatui/latest/ratatui/
  repository: https://github.com/ratatui/ratatui
  
extra:
  recipe-maintainers:
    - phreed
