= freetakserver-ui
:version: 2.2.1


// GENERATED CONTENT START

An optional UI for FreeTAKServer

== Description

This FreeTAKServer UI repository hosts the web user interface for the FreeTAKServer project. It is built using Python with Flask, employing additional technologies such as SQLite for database management, Alembic for database schema migrations, and Flask_Login for session-based authentication. The UI supports various features like modular design through Flask Blueprints, forms validation, and provides a dashboard for server management. The front-end utilizes HTML, CSS, SCSS, and JavaScript, making it a comprehensive tool for administrators to manage the FreeTAKServer. The project is licensed under the EPL/MIT License.

== Links

* Homepage: https://github.com/FreeTAKTeam/UI
* Documentation: https://freetakteam.github.io/FreeTAKServer-User-Docs/

== Package Information

* **License**: MIT
* **Version**: 2.2.1
* **Architecture**: No-architecture (pure python)

== Requirements

=== Host Requirements

* pip
* python ==${{ python_min }}
* poetry-core

=== Run Requirements

* python >=${{ python_min }},<4.0.0
* alembic 1.13.1.*
* blinker 1.7.0.*
* certifi 2024.2.2.*
* charset-normalizer 3.3.2.*
* click 8.1.7.*
* colorama >= 0.4.6
* dnspython 2.6.1.*
* email_validator 2.1.1.*
* eventlet 0.35.2.*
* flask 3.0.2.*
* flask-cors 4.0.0.*
* flask-login 0.6.3.*
* flask-migrate 4.0.6.*
* flask-sqlalchemy 3.1.1.*
* flask-wtf 1.2.1.*
* greenlet 3.1.1.*
* gunicorn 21.2.0.*
* idna 3.6.*
* itsdangerous 2.1.2.*
* jinja2 3.1.3.*
* mako 1.3.2.*
* markupsafe 2.1.5.*
* packaging 24.0.*
* python-decouple 3.8.*
* requests 2.31.0.*
* sqlalchemy 2.0.38.*
* sqlalchemy-utils 0.41.1.*
* typing_extensions 4.10.0.*
* urllib3 2.2.1.*
* werkzeug 3.0.1.*
* wtforms 2.3.3.*

== Installation

This package is built using rattler-build and can be installed using mamba or conda:

[source,bash]
----
pixi global install -c meso-forge freetakserver-ui
----

== Maintainers

* phreed

---

_This portion of the README was generated from the recipe.yaml file._

_Last updated: 2025-06-11_

// GENERATED CONTENT END

https://github.com/prefix-dev/recipe-format
