# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "24.01.0"

package:
  name: poppler
  version: ${{ version }}

source:
  url: https://poppler.freedesktop.org/poppler-${{ version }}.tar.xz
  sha256: c7def693a7a492830f49d497a80cc6b9c85cb57b15e9be2d2d615153b79cae08

# The `install` command will take care of copying the files to the right place
build:
  script: |
    extra_cmake_args=(
    -GNinja
    -DCMAKE_INSTALL_LIBDIR=lib
    -DENABLE_UNSTABLE_API_ABI_HEADERS=ON
    -DENABLE_GPGME=OFF
    -DENABLE_LIBCURL=OFF
    -DENABLE_LIBOPENJPEG=openjpeg2
    -DENABLE_QT6=OFF
    -DENABLE_QT5=OFF
    -DENABLE_NSS3=OFF
    )
    mkdir build && cd build
    cmake ${CMAKE_ARGS} "${extra_cmake_args[@]}" \
      -DCMAKE_PREFIX_PATH=$PREFIX \
      -DCMAKE_INSTALL_PREFIX=$PREFIX \
      -DTIFF_INCLUDE_DIR=$PREFIX/include \
      $SRC_DIR
    ninja
    ninja install

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - pkg-config
    - cmake
    - ninja
  host:
    - cairo
    - fontconfig
    - freetype
    - glib
    - libboost-headers
    - libjpeg-turbo
    - lcms2
    - libiconv
    - libpng
    - libtiff
    - openjpeg
    - zlib

tests:
  - script:
      - pdfinfo -listenc
      - pdfunite --help
      - pdftocairo --help

about:
  homepage: https://poppler.freedesktop.org/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: PDF rendering library based on the xpdf-3.0 code base
  description: |
    Poppler is a PDF rendering library based on the xpdf-3.0 code base.
    It provides a set of utilities for getting information of PDF documents
    and converting them to other formats.
  documentation: https://poppler.freedesktop.org/
  repository: https://gitlab.freedesktop.org/poppler/poppler

extra:
  recipe-maintainers:
    - phreed
