# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 1.35.0

package:
  version: ${{ version }}
  name: mediamtx
  
source:
  url: https://github.com/kubernetes/kompose/archive/refs/tags/v${{ version }}.tar.gz
  sha256: cdd46bbbfe2be95057df8eb5016b88328063255c38e0e42d27abccd7d3ebbad6
  target_directory: src/kompose

build:
  number: 0
  script:
    - cd src/kompose
    - go generate ./...
    - CGO_ENABLED=0 go build .
    # s="-s -w -X=github.com/${{ group }}/${{ name }}/version.Version=${{ version }} -X=github.com/${{ group }}/${{ name }}/server.mode=release" 
    #     -o $PREFIX/bin/${{ name }}
    # - go-licenses save . --save_path ../../library_licenses
    #     --ignore=golang.org/x/crypto/internal/poly1305
    #     --ignore=golang.org/x/crypto/salsa20/salsa
    #     --ignore=golang.org/x/sys/unix
    #     --ignore=golang.org/x/crypto/argon2
    #     --ignore=golang.org/x/crypto/blake2b
    #     --ignore=golang.org/x/sys/cpu
    #     --ignore=golang.org/x/crypto/sha3
    #     --ignore=github.com/ugorji/go/codec
    #     --ignore=github.com/benburkert/openpgp

requirements:
  build:
    - cmake
    - ${{ compiler('go') }}
    # - ${{ stdlib('c') }}
    - go-licenses

tests:
  - script: | 
      kompose --help 2>&1  | grep "${{ version }}"

about:
  homepage: https://kompose.io/ 
  summary: Kompose is a conversion tool for Docker Compose to container orchestrators
  description: |
    Kompose is a conversion tool for Docker Compose to container orchestrators
    such as Kubernetes or OpenShift.
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses
  documentation: https://kompose.io/user-guide/
  repository: ttps://github.com/bluenviron/mediamtx

extra:
  recipe-maintainers:
    - phreed
