# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

# Much of the information is available via:
#  pnpm info node-red-contrib-web-worldmap
# The sha256 is currently not available from these sources. 
context:
  name: node-red-contrib-web-worldmap
  version: "5.1.2"
  sha: 06db0a456ec02c74954b6e01400da3f881835c3384617c63d788f95b444291ae 

package:
  name: node-red-contrib-web-worldmap
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/${{ name }}/-/${{ name }}-${{ version }}.tgz
  sha256: ${{ sha }}
 
build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - node-red
    - pnpm
    - pnpm-licenses
  host:
    - nodejs
  run:
    - nodejs

tests:
  - script: 
      - "echo 'not sure how to test'"

about:
  homepage: https://github.com/dceejay/RedMap#readme
  summary: 'A Node-RED node to provide a world map web page for plotting "things" on.'
  description: |
     Plots "things" on a map.
     By default the map will be served from {httpRoot}/worldmap,
     but this can be changed in the configuration panel.
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - https://github.com/dceejay/RedMap/blob/master/LICENSE
    - third-party-licenses.txt
  documentation: https://github.com/dceejay/RedMap#readme
  repository: https://github.com/dceejay/RedMap

extra:
  recipe-maintainers:
    - phreed
