# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2.3.19

package:
  name: asciidoctor-pdf
  version: ${{ version }}

source:
  - url: https://rubygems.org/downloads/asciidoctor-pdf-${{ version }}.gem
    sha256: 034a142964d627b82fd4f08a094abedae981e632e7f1c501d3bd9c2dfbe073f9
  - path: asciidoctor-pdf.bat
  - path: asciidoctor-pdf.sh

build:
  noarch: generic
  script:
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin asciidoctor-pdf-${{ version }}.gem
    - gem unpack asciidoctor-pdf-${{ version }}.gem
    - cp -v asciidoctor-pdf.bat $PREFIX/bin/asciidoctor-pdf.bat
    - cp -v asciidoctor-pdf.sh $PREFIX/bin/asciidoctor-pdf

requirements:
  host:
    - ruby
  run:
    - ${{ pin_compatible('ruby', upper_bound='x.x') }}
    - asciidoctor >=2.0,<3.0
    - rb-concurrent-ruby >=1.1,<2.0
    - rb-matrix >=0.4,<1.0
    - rb-prawn >=2.4.0,<2.5.0
    - rb-prawn-icon >=3.0.0,<3.1.0
    - rb-prawn-svg >=0.34.0,<0.35.0
    - rb-prawn-table >=0.2.0,<0.3.0
    - rb-prawn-templates >=0.1.0,<0.2.0
    - rb-treetop >=1.6.0,<1.7.0
    - rb-ttfunk >=1.7.0,<1.8.0

tests:
  - script:
      - asciidoctor-pdf -v

about:
  homepage: https://asciidoctor-pdf.org
  license: MIT
  license_file: asciidoctor-pdf-${{ version }}/LICENSE
  summary: An AsciiDoc to PDF processor
  description: |
    A fast, open source text processor and publishing toolchain
    for converting AsciiDoc content to PDF.
  documentation: https://www.rubydoc.info/gems/asciidoctor-pdf
  repository: https://github.com/asciidoctor/asciidoctor-pdf

extra:
  recipe-maintainers:
    - phreed
