# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.3.15"
  python_min: 3.11
  python_max: 3.12

package:
  name: digitalpy
  version: ${{ version }}

source:
  url: https://github.com/FreeTAKTeam/DigitalPy/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 75a8970465e290f61b633595ff12cf39ad5bd0cc98d5efcf9d860912f8134dc3

build:
  noarch: python
  script: pip install . -v

requirements:
  host:
    - pip
    - python >=${{ python_min }},<${{ python_max }}
    - setuptools
    - wheel
    - poetry-core
    - flask-cors
    - flask-jwt-extended
    - lxml
    - opentelemetry-sdk
    - psutil
    - requests
    - ruamel.yaml
    - sqlalchemy
    - xmltodict
    - cryptography
    - jinja2
    - packaging
    - pyyaml
  run:
    - python >=${{ python_min }},<${{ python_max }}
    - rule-engine
    - cryptography
    - packaging
    - pyyaml
    - pyzmq
    - flask-cors
    - flask-jwt-extended
    - lxml
    - opentelemetry-sdk
    - psutil
    - requests
    - ruamel.yaml
    - setuptools
    - sqlalchemy
    - xmltodict
  run_exports:
    - ${{ pin_subpackage("digitalpy", upper_bound="x.x") }}

tests:
  - script:
      interpreter: python
      content: |
        import digitalpy

about:
  homepage: https://github.com/FreeTAKTeam/DigitalPy
  summary: A python implementation of the aphrodite specification
  description: |
    A python implementation of the aphrodite specification,
    heavily based on WCMF.
  license: EPL-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - phreed
