# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.3.15"
  python_min: 3.11
  python_max: 3.12

package:
  name: digitalpy
  version: ${{ version }}

source:
  url: https://api.github.com/repos/FreeTAKTeam/DigitalPy/tarball/refs/tags/v0.3.15
  sha256: 86b36fd8983866f9a19813594a7144fa693613f38db5e7b78a833864b7536052

build:
  noarch: python
  script: pip install . -v

requirements:
  host:
  - pip
  - python >=${{ python_min }},<${{ python_max }}
  - setuptools
  - wheel
  - poetry-core
  - flask-cors
  - flask-jwt-extended
  - lxml
  - opentelemetry-sdk
  - psutil
  - requests
  - ruamel.yaml
  - sqlalchemy
  - xmltodict
  - cryptography
  - jinja2
  - packaging
  - pyyaml
  run:
  - python >=${{ python_min }},<${{ python_max }}
  - rule-engine
  - cryptography
  - packaging
  - pyyaml
  - pyzmq
  - flask-cors
  - flask-jwt-extended
  - lxml
  - opentelemetry-sdk
  - psutil
  - requests
  - ruamel.yaml
  - setuptools
  - sqlalchemy
  - xmltodict
  run_exports:
  - ${{ pin_subpackage("digitalpy", upper_bound="x.x") }}

tests:
  # Test 1: Verify package contents are included
- package_contents:
    files:
        # Python library package
    - site-packages/digitalpy/__init__.py

  # Test 2: Python import test
- script:
    interpreter: python
    content: |
      import digitalpy

about:
  homepage: https://github.com/FreeTAKTeam/DigitalPy
  summary: A python implementation of the aphrodite specification
  description: |
    A python implementation of the aphrodite specification,
    heavily based on WCMF.
  license: EPL-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
  - phreed

  version:
    github-tags:
    - ^(\d+\.\d+\.\d+)$
