schema_version: 1

context:
  name: jank
  group: jank-lang
  version: 0.1.0
  commit: "fe32c9deac434de4b88b9f3e25dc2ca5b1ba925f"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  git: https://github.com/jank-lang/jank.git
  rev: ${{ commit }}
  # url: https://github.com/${{ group }}/${{ name }}/archive/refs/heads/main.zip
  # sha256: ${{ sig }}
  patches:
    - 0001-fix-includes.patch

build:
  number: 0
  script: |
    cd compiler+runtime
    ./bin/configure -GNinja -DCMAKE_BUILD_TYPE=Release
    ./bin/compile

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - binutils
    - clangdev
    - llvmdev
    - ninja
    - pkg-config
    - sbcl
    - sed
  host:
    - libboost-devel
    - if: linux
      then: elfutils
    - fmt
    - gmp
    - libclang-cpp
    - libllvm16

tests:
  - script:
      - ${{ name }} --help

about:
  license: MPL-2.0
  license_file: https://github.com/${{ group }}/${{ name }}/blob/main/LICENSE
  summary: Jank a LLVM hosted Clojure
  homepage: https://jank-lang.org/
  repository: https://github.com/${{ group }}/${{ name }}

extra:
  recipe-maintainers:
    - phreed
