# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.75.0"

package:
  name: devcontainer-cli
  version: ${{ version }}

source:
  url: https://github.com/devcontainers/cli/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 3b7c20f403645d25238562813818de5746d38128415fab08f2423dc754425eec

build:
  number: 0
  script: |
    yarn
    yarn compile

    # Install the CLI entry point
    mkdir -p $PREFIX/bin
    cp devcontainer.js $PREFIX/bin/devcontainer
    chmod +x $PREFIX/bin/devcontainer

    # Install the compiled distribution files
    mkdir -p $PREFIX/lib/devcontainer-cli
    cp -r dist $PREFIX/lib/devcontainer-cli/

    # Update the entry point to use the installed location
    sed -i "s|require('./dist/spec-node/devContainersSpecCLI')|require('$PREFIX/lib/devcontainer-cli/dist/spec-node/devContainersSpecCLI')|" $PREFIX/bin/devcontainer

requirements:
  build:
    - yarn
    - python
    - make
    - ${{ compiler('cxx') }}
    - pkg-config
  host:
    - nodejs
  run:
    - nodejs

tests:
  - script: |
      devcontainer --help
      # stderr:
      #   contains: "Please create a configuration file"
      # exit: 2

about:
  homepage: https://containers.dev/
  license: MIT
  license_file:
    - LICENSE.txt
  summary: Configure Devcontainer CLI
  description: |
    A reference implementation for the specification that
    can create and configure a dev container from a devcontainer.json.
  repository: https://github.com/devcontainers/cli

extra:
  recipe-maintainers:
    - phreed
