# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.1.0

package:
  name: systemd-pixi-generator
  version: ${{ version }}

source:
  url: https://github.com/babeloff/pixi-service-generator/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 73329fe24c53f0ca47cd0939256ca5c4644742cb7c14cf4114c8c9871336d342

build:
  number: 0
  script: |
    cargo install --root $PREFIX --path .
    cargo bundle-licenses --format yaml --output thirdpartylicenses.yaml

requirements:
  build:
    - rust
    - cargo-bundle-licenses

tests:
  - script: |
      systemd-pixi-generator --help

about:
  homepage: https://github.com/babeloff/pixi-service-generator
  license: MIT
  license_file:
    - LICENSE
  summary: A service generator for pixi global packages
  description: |
    A service generator for pixi global packages.
    Generally speaking, services are just a specific type of CLI application
    which is long running, and does so in the background,
    not under the direct control of a login session.

extra:
  recipe-maintainers:
    - phreed
