# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: asyncio
  version: "3.4.3"
  python_min: 3.11.0

package:
  name: asyncio
  version: ${{ version }}

source:
  url: https://github.com/python/asyncio/archive/refs/tags/${{ version }}.tar.gz
  sha256: b22225680ea04c3528b7fa03e9c6d152470173dd3873996b8cb29fcb37799f1b

build:
  noarch: python
  script: pip install . -v

requirements:
  host:
    - pip
    - python >=${{ python_min }}
    - setuptools
    - wheel
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - asyncio

about:
  homepage: http://www.python.org/dev/peps/pep-3156/
  summary: reference implementation of PEP 3156
  license: Apache-2.0
  license_file: COPYING

extra:
  recipe-maintainers:
    - phreed