# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: asyncio
  version: "3.4.3"
  python_min: 3.11.0

package:
  name: asyncio
  version: ${{ version }}

source:
  url: https://github.com/python/asyncio/archive/refs/tags/${{ version }}.tar.gz
  sha256: b22225680ea04c3528b7fa03e9c6d152470173dd3873996b8cb29fcb37799f1b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python ==${{ python_min }}
    - pip
    - setuptools
  host:
    - cryptography
    - jinja2
    - packaging
    - pyyaml
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - asyncio
      pip_check: true

about:
  homepage: http://www.python.org/dev/peps/pep-3156/
  summary: reference implementation of PEP 3156
  license: Apache-2.0
  license_file: COPYING

extra:
  recipe-maintainers:
    - phreed