# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.53.1

package:
  name: opendal-oli
  version: ${{ version }}

source:
  url: https://github.com/apache/opendal/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 46670295e2323fc2f826750cdcfb2692fbdbea87122fe530a07c50c8dba1d3d7

build:
  script:
    - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml  # !(1)
    - $BUILD_PREFIX/bin/cargo install --locked --bins --root ${PREFIX} --path .

requirements:
  build:
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses

tests:
  - script:
    - oli --help # !(2)

about:
  homepage: https://opendal.apache.org/apps/oli/
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Apache OpenDAL™ Oli
  description: |
    oli stands for OpenDAL Command Line Interface
    oli aims to provide a unified and user-friendly way
    to manipulate data stored in various storage service.
  repository: https://github.com/apache/opendal/tree/main/bin/oli

extra:
  recipe-maintainers:
    - maintainer