# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.53.3"

package:
  name: opendal-oli
  version: ${{ version }}

source:
  url: https://api.github.com/repos/apache/opendal/tarball/refs/tags/v0.53.3
  sha256: 9406070cdcfed6acf55d4c3802e82a1e51fa715cac2cbf74d6f7277a8b56c876

build:
  script:
    interpreter: nu
    content: |
      # Expand the GitHub API tarball which comes as a single file
      let tarball_file = (ls | where type == file and name =~ "\\.tar\\.gz$|^v0\\.53\\.3$" | first | get name)
      ^tar -xzf $tarball_file

      # Find the extracted directory (GitHub API tarballs create directories like "apache-opendal-abc123")
      let extracted_dir = (ls | where type == dir and name =~ "apache-opendal-" | first | get name)

      # Change to the extracted directory and build
      cd $extracted_dir

      # Move to the oli binary directory
      cd bin/oli

      ^cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
      ^cargo install --locked --bins --root ($env.PREFIX) --path .

requirements:
  build:
    - nushell
    - tar
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses

tests:
  # Test 1: Verify package contents are included
  - package_contents:
      files:
        # OpenDAL oli binary
        - ${{ "Library/" if win }}bin/oli${{ ".exe" if win }}

    # Test 2: Functional test
  - requirements:
      build:
        - nushell
    script:
      interpreter: nu
      content:
        - ^oli --help # !(2)

about:
  homepage: https://opendal.apache.org/apps/oli/
  license: Apache-2.0
  license_file:
    - "*/LICENSE"
    - "*/bin/oli/THIRDPARTY.yml"
  summary: Apache OpenDAL™ Oli
  description: |
    oli stands for OpenDAL Command Line Interface
    oli aims to provide a unified and user-friendly way
    to manipulate data stored in various storage service.
  repository: https://github.com/apache/opendal/tree/main/bin/oli

extra:
  recipe-maintainers:
    - phreed
  version:
    github-tags:
      - ^(\d+\.\d+\.\d+)
