# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/73cd2eed94c576213c5f25ab57adf6d8c83e792a/schema.json
schema_version: 1

context:
  version: "10.2.0"

package:
  name: fd
  version: ${{ version }}

source:
  url: https://github.com/sharkdp/fd/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 73329fe24c53f0ca47cd0939256ca5c4644742cb7c14cf4114c8c9871336d342

build:
  number: 0
  script: |
    cargo install --root $PREFIX --path .
    $PREFIX/bin/fd --gen-completions bash > fd.bash
    $PREFIX/bin/fd --gen-completions fish > fd.fish
    mkdir -p $PREFIX/share/bash-completion/completions
    mkdir -p $PREFIX/share/fish/vendor_completions.d
    cp fd.bash $PREFIX/share/bash-completion/completions/fd
    cp fd.fish $PREFIX/share/fish/vendor_completions.d/fd.fish
    cp contrib/completion/_fd $PREFIX/share/zsh/site-functions/_fd
    cp doc/fd.1 $PREFIX/share/man/man1/fd.1

requirements:
  build:
    - rust
    - cargo

tests:
  - script: |
      touch foo_file
      touch test_file
      test "$(fd test)" = "test_file"

about:
  homepage: https://github.com/sharkdp/fd
  license: Apache-2.0 OR MIT
  license_file: LICENSE
  summary: Simple, fast and user-friendly alternative to find
  description: |
    fd is a simple, fast and user-friendly alternative to find.
    While it does not seek to mirror all of find's powerful functionality,
    it provides sensible (opinionated) defaults for 80% of the use cases.

extra:
  recipe-maintainers:
    - phreed
