# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 1.5.1

package:
  name: internxt-cli
  version: ${{ version }}

source:
  - url: https://github.com/internxt/cli/archive/refs/tags/v{{ version }}.tar.gz
    sha256: d3386f45d336bc1987e63a8e594e353c71e50a12c9c6d7e36c4b31af6cccfc19

build:
  number: 0
  noarch: generic
  script: |
    # Create tarball from the current project, similar to `npm pack`
    pnpm pack --ignore-scripts

    # Install the tarball globally and from source
    export npm_config_build_from_source=true
    pnpm add --global "${SRC_DIR}/${PKG_NAME}-${PKG_VERSION}.tgz"

    # Create license report for dependencies
    pnpm install
    pnpm-licenses generate-disclaimer --prod --output-file=third-party-licenses.txt


requirements:
  build:
    - nodejs
    - grunt
    - pnpm
    - pnpm-licenses
  host:
    - nodejs
    - grunt
  run:
    - nodejs

tests:
  - script:
    - ls
      # - "find . -maxdepth 2"
      # - "internxt --help 2>&1"

about:
  homepage: https://github.com/internxt/cli/blob/main/README.md
  summary: A CLI tool to interact with your Internxt encrypted files
  description: |
    rotect your privacy with our open-source and post-quantum encrypted suite of secure services.
    Private by default, secure by design, and free as in freedom.
  license: AGPL-3.0
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  documentation: https://github.com/internxt/cli/blob/main/README.md
  repository: https://github.com/internxt/cli

extra:
  recipe-maintainers:
    - phreed
