# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.5.3"

package:
  name: internxt-cli
  version: ${{ version }}

source:
  - url: https://api.github.com/repos/internxt/cli/tarball/v1.5.3
    sha256: 4c5eedf4a9dff5d53080070d3c66d44819beb80d8bb418e7542331af14444ead
    target_directory: internxt-cli-src

build:
  number: 0
  noarch: generic
  script:
    interpreter: nu
    content: |
      $env.YARN_ENABLE_IMMUTABLE_INSTALLS = "false"
      # Install dependencies first (required for prepack script)
      ^yarn install

      # Create tarball from the current project, similar to `npm pack`
      ^yarn pack

      # Install the tarball to the conda environment prefix
      ^npm install --prefix=($env.PREFIX) --global ($env.SRC_DIR | path join "package.tgz")

      # Create license report for dependencies
      # First install with pnpm to generate lockfile
      ^pnpm install
      ^pnpm-licenses generate-disclaimer --prod --output-file=third-party-licenses.txt

requirements:
  build:
    - nushell
    - nodejs
    - grunt
    - pnpm
    - pnpm-licenses
    - yarn
    - python
    - setuptools
    - ${{ compiler('cxx') }}
    - make
  host:
    - nodejs
    - grunt
  run:
    - nodejs

tests:
  # Test 1: Verify package contents are included
  - package_contents:
      files:
        # Internxt CLI binary
        - ${{ "Library/" if win }}bin/internxt${{ ".cmd" if win }}
          # Node.js package files
        - ${{ "Library/" if win }}lib/node_modules/@internxt/cli/package.json

    # Test 2: Functional tests
  - requirements:
      build:
        - nushell
    script:
      interpreter: nu
      content:
        - ^internxt --help
        - ^internxt --version

about:
  homepage: https://github.com/internxt/cli/blob/main/README.md
  summary: A CLI tool to interact with your Internxt encrypted files
  description: |
    rotect your privacy with our open-source and post-quantum encrypted suite of secure services.
    Private by default, secure by design, and free as in freedom.
  license: AGPL-3.0
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  documentation: https://github.com/internxt/cli/blob/main/README.md
  repository: https://github.com/internxt/cli

extra:
  recipe-maintainers:
    - phreed
