# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 1.5.1

package:
  name: internxt-cli
  version: ${{ version }}

source:
  - url: https://github.com/internxt/cli/archive/refs/tags/v${{ version }}.tar.gz
    sha256: ee91c9fce279cdf6c63130bd13b7a8f06fa59013ac0659d22f203f7818d55b9f

build:
  number: 0
  noarch: generic
  script:
    interpreter: nu
    content: |
      # Install dependencies first (required for prepack script)
      ^yarn install

      # Create tarball from the current project, similar to `npm pack`
      ^yarn pack

      # Install the tarball to the conda environment prefix
      ^npm install --prefix=($env.PREFIX) --global ($env.SRC_DIR | path join "package.tgz")

      # Create license report for dependencies
      # First install with pnpm to generate lockfile
      ^pnpm install
      ^pnpm-licenses generate-disclaimer --prod --output-file=third-party-licenses.txt

requirements:
  build:
    - nushell
    - nodejs
    - grunt
    - pnpm
    - pnpm-licenses
    - yarn
    - python
    - setuptools
    - ${{ compiler('cxx') }}
    - make
  host:
    - nodejs
    - grunt
  run:
    - nodejs

tests:
  - requirements:
      build:
        - nushell
    script:
      interpreter: nu
      content:
        - ^internxt --help
        - ^internxt --version

about:
  homepage: https://github.com/internxt/cli/blob/main/README.md
  summary: A CLI tool to interact with your Internxt encrypted files
  description: |
    rotect your privacy with our open-source and post-quantum encrypted suite of secure services.
    Private by default, secure by design, and free as in freedom.
  license: AGPL-3.0
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  documentation: https://github.com/internxt/cli/blob/main/README.md
  repository: https://github.com/internxt/cli

extra:
  recipe-maintainers:
    - phreed
