# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

# Much of the information is available via:
#  pnpm info node-red
# The sha256 is currently not available from these sources. 
context:
  name: node-red
  version: 4.0.9

package:
  name: node-red
  version: ${{ version }}

source:
  - url: https://github.com/node-red/node-red/archive/refs/tags/${{ version }}.tar.gz
    sha256: d3386f45d336bc1987e63a8e594e353c71e50a12c9c6d7e36c4b31af6cccfc19
    file_name: node-red-${{ version }}.tgz
  - if: linux
    then: 
      path: systemd/configure-service.sh
      target_directory: systemd/configure-node-red.sh
 
build:
  number: 0
  noarch: generic
  script: 
    interpreter: nu
    content: 
      - npm add -g ./node-red-${{ version }}.tgz --prefix ${{ PREFIX }}
#       - rg --ignore-case --files --glob '*license*' ../node_modules
#       mkdir collected-licenses

# # Find license files and copy them with unique names
# ls node_modules/** | where type == file and (name | str downcase | str contains "license") | each {|file|
#     let sanitized_name = ($file.name | str replace -a "/" "_" )
#     cp $file.path (["collected-licenses", $sanitized_name] | path join)
# }
#       mkdir -p collected-licenses

# find node_modules -type f \( -iname "license" -o -iname "license.md" -o -iname "license.txt" \) | while read -r file; do
#   # Generate a unique filename using package path and basename
#   sanitized_path=$(echo "$file" | sed 's|[\/]|_|g')
#   cp "$file" "collected-licenses/${sanitized_path}"
# done


requirements:
  build:
    - nodejs
    - ripgrep
  host:
    - nodejs
    - grunt
  run:
    - nodejs

tests:
  - script:
      - "node-red --help 2>&1"
      # - "find . -maxdepth 2" 

about:
  homepage: https://nodered.org
  summary: 'Low-code programming for event-driven applications'
  description: |
     Node-RED's goal is to enable anyone to build applications that collect,
     transform and visualize their data; 
     building flows that can automate their world. 
     Its low-code nature makes it accessible to users of any background, 
     whether for home automation,
     industrial control systems or anything in between.
  license: Apache-2.0
  license_file:
    - LICENSE # https://github.com/node-red/node-red/blob/master/LICENSE
    # - lib/node_modules/node-red/node_modules/
  documentation: https://nodered.org/docs/
  repository: https://github.com/node-red/node-red

extra:
  recipe-maintainers:
    - phreed
