# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.4.0-devel3"

package:
  name: ble-sh
  version: "0.4.0_devel3"

source:
  - url: https://github.com/akinomyoga/ble.sh/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 867ec9681bd75de7faa93622bcae1b705f561c11d83a62ead1f14554b87630dc
  - url: https://github.com/akinomyoga/blesh-contrib/archive/refs/heads/master.tar.gz
    sha256: a2147dc083ec0cc0f495b1ae68eb1dcddf5e4b29750d6f28e6d2cf003f6d4515
    target_directory: contrib-src

build:
  noarch: generic
  script:
    interpreter: nu
    content: |
      # Create dummy .git directory for Makefile dependency
      ^mkdir -p .git

      # Copy contrib files from the second source
      ^cp -r contrib-src/* contrib/

      # Build ble.sh from source (define CP variable for contrib.mk)
      ^make -f GNUmakefile CP="cp -p"

      let profile_dir = ($env.PREFIX | path join "etc" "profile.d")
      let blesh_dir = ($env.PREFIX | path join "share" "blesh")
      ^mkdir -p $profile_dir
      ^mkdir -p $blesh_dir

      # Copy the built ble.sh and other necessary files
      ^cp out/ble.sh $blesh_dir
      ^cp -r keymap lib contrib docs $blesh_dir
      ^cp README.md LICENSE.md $blesh_dir

      # Create a profile script that sources ble.sh
      let profile_script = $"# Bash Line Editor \(ble.sh\) initialization
      # Source this in your ~/.bashrc with:
      [[ $- == *i* ]] && source ($env.PREFIX)/etc/profile.d/ble.sh --attach=none
      [[ \${BLE_VERSION-} ]] && ble-attach

      if [[ $- == *i* ]]; then
        source ($env.PREFIX)/share/blesh/ble.sh --attach=none
      fi"

      $profile_script | save ($profile_dir | path join "ble.sh")

requirements:
  build:
    - nushell
    - make
    - gawk
  run:
    - bash >=3.0

tests:
  # Test 1: Verify package contents are included
  - package_contents:
      files:
        # Main ble.sh installation
        - share/blesh/ble.sh
        # Profile script
        - etc/profile.d/ble.sh

  # Test 2: Functional test
  - requirements:
      build:
        - nushell
        - bash
    script:
      interpreter: nu
      content: |
        ^test -f ($env.PREFIX | path join "share" "blesh" "ble.sh")
        ^test -f ($env.PREFIX | path join "etc" "profile.d" "ble.sh")

about:
  homepage: https://github.com/akinomyoga/ble.sh
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: Bash Line Editor with syntax highlighting, auto suggestions, vim modes, etc.
  description: |
    ble.sh (Bash Line Editor) is a command line editor written in pure Bash
    which replaces the default GNU Readline. It provides syntax highlighting,
    auto suggestions, vim modes, and many other advanced features for Bash
    interactive sessions. It requires only Bash 3.0+ and basic POSIX utilities.

extra:
  recipe-maintainers:
    - phreed
  version:
    github-release:
      - ^(\d+\.\d+\.\d+)
