# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2.0.2
  python_min: 3.11.0

package:
  name: testresources
  version: ${{ version }}

source:
  url: https://api.github.com/repos/testing-cabal/testresources/tarball/refs/tags/2.0.2
  sha256: bb10c9350e4e5ec62371fda2d364e39299f80955223985c6f01186b173eded52

build:
  noarch: python
  script: pip install . -v

requirements:
  host:
  - pip
  - python ==${{ python_min }}
  - setuptools
  - wheel
  - docutils
  - testtools
  - fixtures
  - cryptography
  - jinja2
  - packaging
  - pyyaml
  run:
  - python >=${{ python_min }},<4.0.0
  - pbr >=1.8
  - cryptography
  - jinja2
  - packaging

tests:
  # Test 1: Verify package contents are included
- package_contents:
    files:
        # Python library package
    - site-packages/testresources/__init__.py

  # Test 2: Python import test
- script:
    interpreter: python
    content: |
      import testresources

about:
  summary: Testresources, a pyunit extension for managing expensive test resources
  license: JSON
  license_file: COPYING
  homepage: https://github.com/testing-cabal/testresources/tags
  repository: https://github.com/testing-cabal/testresources

extra:
  recipe-maintainers:
  - phreed
  version:
    github-tags:
    - ^(\d+\.\d+\.\d+)
