# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2.0.2
  python_min: 3.11.0
  group: babeloff
  # group: testing-cabal

package:
  name: testresources
  version: ${{ version }}

source:
  url: https://github.com/${{ group }}/testresources/archive/refs/tags/${{ version }}.tar.gz
  sha256:  3c96775290b1b377dec66fda3401fdb1961b7467a1eee915a7313575f2aeed4c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ==${{ python_min }}
    - docutils
    - testtools
    - fixtures
    # - pip
    # - setuptools
    - cryptography
    - jinja2
    - packaging
    - pyyaml
  run:
    - python >=${{ python_min }},<4.0.0
    - pbr >=1.8

tests:
  - python:
      imports:
        - testresources
      pip_check: true

about:
  summary: Testresources, a pyunit extension for managing expensive test resources
  license: JSON
  license_file: COPYING
  homepage: https://github.com/testing-cabal/testresources/tags
  repository: https://github.com/testing-cabal/testresources

extra:
  recipe-maintainers:
    - phreed