# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/73cd2eed94c576213c5f25ab57adf6d8c83e792a/schema.json
schema_version: 1

context:
  name: digitalpy
  version: 0.3.12
  python_min: 3.11.11

package:
  name: digitalpy
  version: ${{ version }}

source:
  url: https://github.com/FreeTAKTeam/DigitalPy/archive/refs/tags/v${{ version }}.tar.gz
  sha256:  6efc3e9f51ab2b66116c133db56a36666915736c75bc30a54869c1262604c137

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ==${{ python_min }}
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<4.0.0
    - rule-engine
    - pyzmq
  run_exports:
    - ${{ pin_subpackage(name, upper_bound="x.x") }}

tests:
  - python:
      imports:
        - digitalpy
      pip_check: true

about:
  homepage: https://github.com/FreeTAKTeam/DigitalPy
  summary: "A python implementation of the aphrodite's specification, heavily based on WCMF"
  license: EPL-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - phreed
