# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/73cd2eed94c576213c5f25ab57adf6d8c83e792a/schema.json
schema_version: 1

context:
  name: digitalpy
  version: "0.3.15"
  python_min: 3.11

package:
  name: digitalpy
  version: ${{ version }}

source:
  url: https://github.com/FreeTAKTeam/DigitalPy/archive/refs/tags/v${{ version }}.tar.gz
  sha256:  75a8970465e290f61b633595ff12cf39ad5bd0cc98d5efcf9d860912f8134dc3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ==${{ python_min }}
    - poetry-core
    - pip
    - flask-cors
    - flask-jwt-extended
    - lxml
    - opentelemetry-sdk
    - psutil
    - requests
    - ruamel.yaml
    - setuptools
    - sqlalchemy
    - xmltodict
  run:
    - python >=${{ python_min }},<4.0.0
    - rule-engine
    - pyzmq
    - flask-cors
    - flask-jwt-extended
    - lxml
    - opentelemetry-sdk
    - psutil
    - requests
    - ruamel.yaml
    - setuptools
    - sqlalchemy
    - xmltodict
  run_exports:
    - ${{ pin_subpackage(name, upper_bound="x.x") }}

tests:
  - python:
      imports:
        - digitalpy
      pip_check: true

about:
  homepage: https://github.com/FreeTAKTeam/DigitalPy
  summary: "A python implementation of the aphrodite's specification, heavily based on WCMF"
  license: EPL-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - phreed