# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.8.8"

package:
  name: fsarchiver
  version: ${{ version }}

source:
  url: https://github.com/fdupoux/fsarchiver/archive/refs/tags/${{ version }}.tar.gz
  sha256: 99147c7a5e6afdaaf329881e3ccd4ef41bd2e255acfc644989cff15473920da3

build:
  number: 0
  skip: win
  script:
    interpreter: nu
    content: |
      ^autoreconf --force --install --verbose
      ^./configure --prefix=($env.PREFIX) --disable-lzma --sysconfdir=/etc "MKDIR_P=mkdir -p"
      ^make
      ^make install

requirements:
  build:
    - nushell
    - ${{ compiler('c') }}
    # - ${{ stdlib("c") }}
    - make
    - autoconf
    - automake
    - libtool
    - pkg-config
    - zlib
    - bzip2
    - lzo
    - lz4
    - zstd
    - libgcrypt
  host:
    - bzip2
    - e2fsprogs
    - libgcrypt
    - lz4
    - lzo
    - util-linux
    - liblzma
    - zlib
    - zstd

tests:
  # Test 1: Verify package contents are included
  - package_contents:
      files:
        # FSArchiver binary
        - ${{ "Library/" if win }}bin/fsarchiver${{ ".exe" if win }}
        # Man page
        - ${{ "Library/" if win }}share/man/man8/fsarchiver.8

  # Test 2: Functional tests
  - requirements:
      build:
        - nushell
    script:
      interpreter: nu
      content:
        - ^ls
        # - ^fsarchiver usage

about:
  homepage: "https://www.fsarchiver.org"
  license: GPL-2.0-only
  license_file: LICENSE.txt
  summary: File system archiver for linux
  description: |
    FSArchiver is a system tool that allows you to
    save the contents of a filesystem to a compressed archive file.
    The filesystem contents can be restored on a device
    which has a different size and it can be restored on a
    different filesystem.
    Unlike tar/dar, FSArchiver also creates the filesystem
    when it extracts the data to devices.
    Everything is checksummed in the archive
    in order to protect the data. If the archive is corrupt,
    you just lose the current file, not the whole archive.
  repository: https://github.com/fdupoux/fsarchiver

extra:
  recipe-maintainers:
    - phreed
