= node-red-worldmap
:version: 5.1.4


// GENERATED CONTENT START

A Node-RED node to provide a world map web page for plotting "things" on.

== Description

Plots "things" on a map. By default the map will be served from {httpRoot}/worldmap, but this can be changed in the configuration panel.

== Links

* Homepage: https://github.com/dceejay/RedMap#readme
* Repository: https://github.com/dceejay/RedMap

== Package Information

* **License**: Apache-2.0
* **Version**: 5.1.4

== Requirements

=== Host Requirements

* nodejs

=== Run Requirements

* nodejs

=== Build Requirements

* nushell
* nodejs
* node-red

== Installation

This package is built using rattler-build and can be installed using mamba or conda:

[source,bash]
----
pixi global install -c meso-forge node-red-worldmap
----

== Maintainers

* phreed

---

_This portion of the README was generated from the recipe.yaml file._

_Last updated: 2025-06-11_

// GENERATED CONTENT END

`node-red-contrib-web-worldmap` is an nodejs package.

* https://www.npmjs.com/package/node-red-contrib-web-worldmap
* https://flows.nodered.org/search?term=node-red-contrib-web-worldmap&type=node&type=flow&type=collection

== V1 recipe format

https://github.com/prefix-dev/recipe-format
