# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 5.1.4

package:
  name: node-red-worldmap
  version: ${{ version }}

source:
  url: https://github.com/dceejay/RedMap/archive/refs/tags/v5.1.4.tar.gz
  sha256: 0e92d6f4ae0aa3bf9dfb99118cd4468995ee2d50a0a48f9d25246d1f49992b98
  target_directory: node-red-worldmap

build:
  script:
    interpreter: nu
    content: |
      $"building ($env.PKG_NAME)!"

      # Install dependencies in the source directory
      cd node-red-worldmap
      npm install

      # Create target directory and copy files
      let target_dir = $"($env.PREFIX)/lib/node_modules/node-red-contrib-web-worldmap"
      mkdir $target_dir
      cp -r * $target_dir

requirements:
  build:
  - nushell
  - nodejs
  - node-red
  host:
  - nodejs
  run:
  - nodejs

tests:
  # Test 1: Verify package contents are included
- package_contents:
    files:
        # Node-RED Worldmap Node.js package
    - ${{ "Library/" if win }}lib/node_modules/node-red-contrib-web-worldmap/package.json

    # Test 2: Functional test
- requirements:
    build:
    - nushell
  script:
    interpreter: nu
    content:
    - ^echo 'not sure how to test'

about:
  homepage: https://github.com/dceejay/RedMap#readme
  summary: A Node-RED node to provide a world map web page for plotting "things" on.
  description: |
    Plots "things" on a map.
      By default the map will be served from {httpRoot}/worldmap,
      but this can be changed in the configuration panel.
  license: Apache-2.0
  license_file:
  - node-red-worldmap/LICENSE
  documentation: https://github.com/dceejay/RedMap#readme
  repository: https://github.com/dceejay/RedMap

extra:
  recipe-maintainers:
  - phreed
  version:
    github-tags:
    - ^(\d+\.\d+\.\d+)$
