context:
    version: "0.13.1"

package:
  name: temporal
  version: ${{ version }}

source:
  url: https://github.com/temporalio/cli/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 9d8812c96d3404490659fec3915dcd23c4142b421ef4cb7e9622bd9a459e1f74

build:
  number: 0
  # The LDFLAGS are used to set the version of the `temporal` binary. This is a common practice in Go.
  # Build the `temporal` binary and store it in the `$PREFIX/bin` directory.
  # Store the license files in a separate directory in the $SRC_DIR. 
  # These are embedded in the package in the `license_file` section.
  script: |
    export LDFLAGS="${LDFLAGS} -s -w -X github.com/temporalio/cli/temporalcli.Version=${PKG_VERSION}"
    go build -ldflags "$LDFLAGS" -o $PREFIX/bin/temporal ./cmd/temporal
    go-licenses save ./cmd/temporal --save_path="$SRC_DIR/license-files/" || true

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - temporal --version

about:
  homepage: https://temporal.io
  repository: https://github.com/temporalio/cli
  documentation: https://docs.temporal.io/cli
  summary: Temporal CLI
  description: |
    Command-line interface for running Temporal Server and interacting with
    Workflows, Activities, Namespaces, and other parts of Temporal.
  license: MIT
  license_file:
    - LICENSE
    # These license files are generated at build time in the `build.sh` script
    # from all the dependencies of `temporal.io`.
    - license-files/
