# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2025.2.0

package:
  name: bitwarden-cli
  version: ${{ version }}

source:
  url: https://github.com/bitwarden/clients/archive/refs/tags/cli-v${{ version }}.tar.gz
  sha256: 2c31f8f66e197d5bcbc656c258d4556c97e49a940cabad3ec76ff3742b5252c7

build:
  number: 0
  noarch: generic
  script: |
    cd apps/cli
    yarn add @electron/rebuild
    yarn install
    yarn compile
    # yarn build
    # npm install webpack webpack-cli --save-dev
    # npm run build:oss:watch

requirements:
  build:
    - yarn
    - webpack-cli
  host:
    - nodejs
    - jest

  run:

tests:
  - script:
      - bw

about:
  homepage: https://bitwarden.com/help/cli/
  summary: The Bitwarden command-line interface (CLI)
  description: |
    The Bitwarden command-line interface (CLI) is a powerful,
    fully-featured tool for accessing and managing your vault.
    Most features that you find in other Bitwarden client applications
    (desktop, browser extension, etc.)
    are available from the CLI.
    https://contributing.bitwarden.com/getting-started/clients/cli/
  license: Apache-2.0
  license_file: COPYING
  repository: https://github.com/bitwarden/clients/tree/main/apps/cli

extra:
  recipe-maintainers:
    - phreed
