context:
  version: "1.14.0"

package:
  name: bibtex-tidy
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/bibtex-tidy/-/bibtex-tidy-${{ version }}.tgz
  sha256: 0a2c1bb73911a7cee36a30ce1fc86feffe39b2d39acd4c94d02aac6f84a00285
  # we do not extract the source code and install the tarball directly as that works better
  file_name: bibtex-tidy-${{ version }}.tgz

build:
  number: 0
  script:
    # we use NPM to globally install the bibtex-tidy package
    - npm install -g bibtex-tidy-${{ version }}.tgz --prefix ${{ PREFIX }}

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
    - bibtex-tidy --version