# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.0.0"

package:
  name: gemname
  version: ${{ version }}

source:
  - url: https://rubygems.org/downloads/gemname-${{ version }}.gem
    sha256: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

build:
  number: 0
  # For pure Ruby gems (no native extensions)
  noarch: generic

  script:
    # Standard gem installation - the -n flag automatically creates CLI executables
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin gemname-${{ version }}.gem

    # Extract license file
    - gem unpack gemname-${{ version }}.gem
    - cp gemname-${{ version }}/LICENSE* LICENSE || cp gemname-${{ version }}/LICENSE.* LICENSE || echo "No LICENSE file found"

  # For gems with native extensions, remove 'noarch: generic' above and add build requirements below

requirements:
  # For gems with native extensions, add build section:
  # build:
  #   - if: unix
  #     then: ${{ compiler('c') }}
  #   - if: unix
  #     then: ${{ compiler('cxx') }}
  #   - if: win
  #     then: ${{ compiler('m2w64_c') }}
  #   - if: win
  #     then: ${{ compiler('m2w64_cxx') }}

  host:
    - ruby
    # Add other build dependencies here

  run:
    - ${{ pin_compatible('ruby', upper_bound='x.x') }}
    # Add runtime dependencies here with rb- prefix for Ruby gems:
    # - rb-activesupport >=6.0,<8.0
    # - rb-nokogiri >=1.10,<2.0

tests:
  - script:
      # Test gem can be required
      - ruby -r gemname -e 'exit 0'

      # Test CLI tools if gem provides them (CLI tools are automatically created by gem install -n)
      # - gemname --version
      # - gemname --help

about:
  homepage: https://github.com/username/gemname
  repository: https://github.com/username/gemname
  documentation: https://rubydoc.info/gems/gemname

  license: MIT
  license_file: LICENSE

  summary: Brief description of the gem
  description: |
    Longer description of what the gem does.
    Include main features and use cases.

extra:
  recipe-maintainers:
    - maintainer1
