# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 5.2.0

package:
  name: asciidoctor-revealjs
  version: ${{ version }}

source:
  - url: https://rubygems.org/downloads/asciidoctor-revealjs-${{ version }}.gem
    sha256: 3504a5e7eaf2c91de37f96189314ffb1e6bf94dad9d646d5c9a24c6691bf6ae2
  - path: asciidoctor-revealjs.bat
  - path: asciidoctor-revealjs.sh

build:
  number: 0
  script: |
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin asciidoctor-revealjs-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
    - cp -v asciidoctor-revealjs.bat $PREFIX/bin/asciidoctor-revealjs.bat
    - cp -v asciidoctor-revealjs.sh $PREFIX/bin/asciidoctor-revealjs

requirements:
  host:
    - ruby
  run:
    - ${{ pin_compatible('ruby', upper_bound='x.x') }}
    

tests:
  - script: |
      - ruby -r asciidoctor -e 'exit 0'
      - asciidoctor-revealjs -V

about:
  homepage: https://github.com/asciidoctor/asciidoctor-reveal.js
  license: MIT
  license_file: LICENSE.adoc
  summary:  A reveal.js converter for Asciidoctor and Asciidoctor.js. Write your slides in AsciiDoc! 
  description: |
    Asciidoctor reveal.js is a converter for Asciidoctor and Asciidoctor.js 
    that transforms an AsciiDoc document into an HTML5 presentation 
    designed to be executed by the reveal.js presentation framework.
  repository: https://github.com/asciidoctor/asciidoctor-reveal.js

extra:
  recipe-maintainers:
    - phreed
