# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.11.9"

package:
  name: cargo-edit
  version: ${{ version }}

source:
  url: https://github.com/killercup/cargo-edit/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 46670295e2323fc2f826750cdcfb2692fbdbea87122fe530a07c50c8dba1d3d7

build:
  number: 0
  script: |
    # Bundle third-party licenses for compliance
    cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
    # Install the package using cargo
    cargo install --locked --bins --root ${PREFIX} --path .

requirements:
  build:
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host: []
  run: []

tests:
  - requirements:
      build:
        - nushell
    script:
      interpreter: nu
      content:
        # Test that the installed cargo subcommand can execute and show version
        - ^cargo-upgrade --version

about:
  homepage: https://github.com/killercup/cargo-edit
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: "A utility for managing cargo dependencies from the command line."
  summary: "A utility for managing cargo dependencies from the command line."

extra:
  recipe-maintainers:
    - maintainer
  # Notes for Rust packages:
  # - Use cargo install for installation (preferred over manual compilation)
  # - Include cargo-bundle-licenses for license compliance
  # - Test with --version to avoid network/functionality dependencies
  # - Keep host/run requirements minimal unless specific system deps needed
  # - Version numbers cannot contain dashes, use underscores instead
  # - Remove conflicting dependencies that might override Cargo.toml versions
