context:
  major_version: "5.14"
  version: "5.14.0"
  # major_version: "5.16"
  # version: "5.16.0"

package:
  name: gtksourceview5
  version: ${{ version }}

source:
  url: https://download.gnome.org/sources/gtksourceview/${{ major_version }}/gtksourceview-${{ version }}.tar.xz
  sha256: c40d1f7309d111f5805fec47c1fead519c4b8d506317ce5e90013ce47d65e9c6
  # sha256: ab35d420102f3e8b055dd3b8642d3a48209f888189e6254d0ffb4b6a7e8c3566

build:
  script: |
    export PKG_CONFIG_PATH="$BUILD_PREFIX/lib/pkgconfig:$PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
    meson setup build --prefix=$PREFIX \
      -Dintrospection=disabled \
      -Dvapi=false \
      -Dsysprof=false \
      --wrap-mode=nofallback
    meson compile -C build --verbose
    meson install -C build

requirements:
  build:
    - c-compiler
    - cxx-compiler
    - meson
    - ninja
    - pkgconf
    - pkg-config
    - gtk4
    - glib
    - zlib
    - expat
    - fontconfig
    - xorg-xproto
    - xorg-kbproto
    - xorg-xextproto
    - xorg-renderproto
    - liblzma-devel
    - xorg-libx11
    - xorg-libxext
    - xorg-libxrender
    - xorg-libxi
    - xorg-libxfixes
    - xorg-libxcursor
    - xorg-libxdamage
    - xorg-libxrandr
    - cairo
    - pango
    - gdk-pixbuf
    - harfbuzz
    - freetype
    - libpng

  host:
    - cairo
    - fontconfig
    - fribidi
    - gdk-pixbuf
    - glib
    - libglib
    - glib-tools
    - gtk4
    - pango
    - pcre2
    - libxml2

tests:
  - script: |
      cat << EOF > test.c
      #include <gtksourceview/gtksource.h>

      int main(int argc, char *argv[]) {
        gchar *text = gtk_source_utils_unescape_search_text("hello world");
        return 0;
      }
      EOF
      $CC test.c -o test $(pkgconf --cflags --libs gtksourceview-5)
      ./test
    requirements:
      run:
        - pkgconf

about:
  homepage: https://projects.gnome.org/gtksourceview/
  license: LGPL-2.1-or-later
  summary: Text view with syntax, undo/redo, and text marks
  description: |
    GtkSourceView is a text widget that extends the standard GTK text widget GtkTextView.
    It improves GtkTextView by implementing syntax highlighting and other features
    typical of a source code editor.
    This package provides the development files for building applications that use GtkSourceView.
