name: Build and Publish Packages (Deprecated)

# ⚠️  DEPRECATED WORKFLOW ⚠️
#
# This workflow has been split into two separate workflows for better organization:
# 1. build-packages-ci.yml - Builds packages and creates artifacts
# 2. publish-packages.yml - Downloads artifacts and publishes packages
#
# This file is kept for reference but is no longer active.
# Please use the new workflows instead.

on:
  # Disabled - remove the 'on' triggers to prevent this workflow from running
  workflow_dispatch:
    inputs:
      deprecated_notice:
        description: "This workflow is deprecated. Use build-packages-ci.yml and publish-packages.yml instead."
        required: false
        default: "acknowledged"

jobs:
  deprecated-notice:
    name: Deprecated Workflow Notice
    runs-on: ubuntu-latest
    steps:
      - name: Show deprecation notice
        run: |
          echo "🚨 This workflow is deprecated!"
          echo ""
          echo "Please use the new split workflows:"
          echo "1. .github/workflows/build-packages-ci.yml - For building packages"
          echo "2. .github/workflows/publish-packages.yml - For publishing packages"
          echo ""
          echo "The new workflows provide:"
          echo "- Better separation of build and publish steps"
          echo "- Artifact-based workflow communication"
          echo "- No publishing on pull requests"
          echo "- Ability to re-publish without rebuilding"
          exit 1
