= TAKProto Package

This package provides TAKProto, a Python module for encoding & decoding TAK Protocol Payloads.

== About TAKProto

TAKProto is a Python module for encoding & decoding TAK Protocol Payloads, for use with https://www.tak.gov/[TAK Products] including ATAK, WinTAK, iTAK, TAKX, TAK Tracker & TAK Server. TAKProto includes functions for converting TAK Protocol Protobuf messages to Python objects, and serializing CoT XML messages as Protobuf.

=== Features

* *Encode and Decode TAK Data*: Convert between TAK Protocol formats
* *Protobuf Support*: Handle TAK Protocol Protobuf messages
* *XML to Protobuf*: Serialize CoT XML messages as Protobuf
* *Python Objects*: Convert TAK Protocol messages to Python objects
* *Multi-Platform*: Support for ATAK, WinTAK, iTAK, TAKX, TAK Tracker & TAK Server

=== Use Cases

TAKProto is ideal for:

* Building TAK protocol parsers and processors
* Converting between TAK data formats
* Creating TAK-compatible data pipelines
* Developing TAK protocol analysis tools
* Integrating TAK data with other systems
* Building custom TAK protocol handlers

== Package Information

* *Source*: https://github.com/snstac/takproto
* *Documentation*: https://takproto.readthedocs.io/
* *License*: MIT
* *Version*: 3.0.1

== Installation

This package is installed as part of the meso-forge ecosystem and provides the `takproto` Python module.

== Usage

[source,python]
----
import takproto

# Convert XML to Protobuf
proto_data = takproto.xml2proto(xml_string)

# Parse protobuf data
parsed_data = takproto.parse_proto(proto_bytes)

# Format time for TAK
formatted_time = takproto.format_time(datetime_obj)

# Access TAK Protocol version info
from takproto.constants import TAKProtoVer
print("TAK Protocol Version:", TAKProtoVer)
----

== Dependencies

TAKProto requires:

* Python 3.6 or later
* protobuf >= 4.21.0

== Support

For issues, questions, or contributions related to this package, please refer to:

* Upstream repository: https://github.com/snstac/takproto
* TAKProto documentation: https://takproto.readthedocs.io/
