# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.0.1"
  python_min: 3.6
  python_max: 3.12

package:
  name: takproto
  version: ${{ version }}

source:
  url: https://github.com/snstac/takproto/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 14c3640f31bfd77ddc1d38fe271c2d51aef761e143a2a422ddd34ffa3f4817ce
  target_directory: takproto

build:
  noarch: python
  script:
    interpreter: nu
    content: |
      # Change to the extracted directory and install
      cd takproto
      ^pip install . -v

requirements:
  build:
    - nushell
    - tar
  host:
    - pip
    - python >=${{ python_min }},<${{ python_max }}
    - setuptools
    - wheel
  run:
    - python >=${{ python_min }},<${{ python_max }}
    - protobuf >=4.21.0
  run_exports:
    - ${{ pin_subpackage("takproto", upper_bound="x.x") }}

tests:
  # Test 1: Verify package contents are included
  - package_contents:
      files:
        # Python library package
        - site-packages/takproto/__init__.py
        - site-packages/takproto/functions.py
        - site-packages/takproto/constants.py
        - site-packages/takproto/proto/__init__.py

  # Test 2: Python import test
  - script:
      interpreter: python
      content: |
        import takproto
        print("TAKProto imported successfully")
        print("TAKProto version:", takproto.__version__)
        # Test basic functionality
        from takproto import xml2proto, parse_proto, format_time
        from takproto.constants import TAKProtoVer

about:
  homepage: https://github.com/snstac/takproto
  summary: TAKProto is a Python package to encode and decode TAK data
  description: |
    TAKProto is a Python module for encoding & decoding TAK Protocol Payloads,
    for use with TAK Products including ATAK, WinTAK, iTAK, TAKX, TAK Tracker & TAK Server.
    TAKProto includes functions for converting TAK Protocol Protobuf messages to Python objects,
    and serializing CoT XML messages as Protobuf.

    Features:
    - Encode and decode TAK Protocol Payloads
    - Convert TAK Protocol Protobuf messages to Python objects
    - Serialize CoT XML messages as Protobuf
    - Support for ATAK, WinTAK, iTAK, TAKX, TAK Tracker & TAK Server
  license: MIT
  license_file: "takproto/LICENSE"

extra:
  recipe-maintainers:
    - phreed

  version:
    github-releases:
      - ^(\d+\.\d+\.\d+)$
